### ISSUE TITLE
getHolidayName type declaration mismatch

### ISSUE THREAD

**Issue by mindofbp** [geoffreyrose/us-holidays#11]
Looks like #9 added in a type declaration for the return from `getHolidayName` but it is not nullable. Calling the method on a non-holiday returns a type error. 

Changing the function declaration to 
` 
public function getHolidayName(): ?string
    {
         ...
    }
`
should do the trick. I'd be happy to author the PR and add in a test but wasn't sure where such a test should go (`Utilities` seems like it could do the trick but don't want to make assumptions about the structure of your repo)

**Comment by geoffreyrose** [comment]
Thanks for letting me know about this. Fix incoming shortly

**Comment by geoffreyrose** [comment]
fixed in v2.3.1
