### ISSUE TITLE
Call to undefined function USHolidays\Traits\Holidays\easter_days()

### ISSUE THREAD

**Issue by TomislavVinkovic** [geoffreyrose/us-holidays#13]
Hello!
I am creating an app in laravel, and have decided to use your library to check if a given date is a holiday. But, when i run this code:
`
public function passes($attribute, $value) {
        $date = Carbon::parse($value);
        return !($date->isWeekend() || $date->isHoliday());
    }
`
it just gives me this error from the title. Have I done something wrong or is it a bug?

**Comment by geoffreyrose** [comment]
Odd. `easter_days()` is a built in php function. https://www.php.net/manual/en/function.easter-days.php. What version of php and Laravel are you using?
