### ISSUE TITLE
Bank holiday logic is wrong.

### ISSUE THREAD

**Issue by treehousetim** [geoffreyrose/us-holidays#8]
I've reviewed your code just a bit so I may be wrong about its intent.

However your docs state:
> if the holiday falls on Saturday, the holiday is observed the previous day (Friday).

The Federal Reserve system does not operate like this.
I have verified this by calling two different local (to me) banks.

# The Federal Reserve Websites

## For bank holidays falling on Saturday, banks are open the preceding Friday.
https://www.frbservices.org/about/holiday-schedules/

## I think the confusion comes from this web page
https://www.federalreserve.gov/aboutthefed/k8.htm
### At the top of the page
> For holidays falling on Saturday, Federal Reserve Banks and Branches will be open the preceding Friday; however, the Board of Governors will be closed
### At the bottom of the page
> * Saturday - the Board of Governors is closed on June 18, 2021, December 24, 2021, December 31, 2021, and November 10, 2023.

**Comment by geoffreyrose** [comment]
Interesting. So the logic for bank holidays is based around when the holiday is observed. I’m pretty sure the federal government follows the logic as I have it. For instance, I think Christmas 2021 was “observed” on Christmas Eve since Christmas Day was a Saturday. I think banks follow the same logic, (besides maybe the federal reserve), but maybe they don’t. Which seems weird. 

I wonder if the federal reserve has special rules for holidays, but banks (Chase, Bank of America, Wells Fargo, etc) follow the federal government holiday calendar.

**Comment by geoffreyrose** [comment]
Might make more sense to name it “Federal Holiday” since banks can in theory be open or closed on any days they want.

**Comment by treehousetim** [comment]
> Interesting. So the logic for bank holidays is based around when the holiday is observed. I’m pretty sure the federal government follows the logic as I have it. For instance, I think Christmas 2021 was “observed” on Christmas Eve since Christmas Day was a Saturday. I think banks follow the same logic, (besides maybe the federal reserve), but maybe they don’t. Which seems weird.
> 
> I wonder if the federal reserve has special rules for holidays, but banks (Chase, Bank of America, Wells Fargo, etc) follow the federal government holiday calendar.

In 2021 there was no bank holiday for Christmas.  Bank branches were free to close on the 24th, but in terms of FedACH and electronic banking, 12/24/2021 (Friday) was a normal banking day.

**Comment by treehousetim** [comment]
I confirmed this with two banks (US Bank) and a local credit union.

I spoke with a colleague who writes enterprise software at a bank and he confirmed what I'm reporting here.  If the holiday falls on a Saturday it is not observed.  If it falls on a Sunday it is observed on Monday.

**Comment by geoffreyrose** [comment]
I’m going to do some more research to confirm but initially I think I’m going to create a new function that checks if it is a federal holiday (that uses the current logic) and update the current bank holiday method to update to follow the correct rules for banks which only are holidays if the holidays falls on Sunday, then it is observed on Monday, but ignore Saturday holidays.
